### ISSUE TITLE
How do I modify the default channel when subscribing

### ISSUE THREAD

**Issue by 1302812800** [FiveOFive/ws-pubsub#2]
Hello, I would like to know how to modify this channel when I subscribe, it is the default 'ABC', now after clicking subscribe, I would like to know how to modify this ABC, thank you, you wrote a great library
![image](https://user-images.githubusercontent.com/55608375/142091754-9c2a21db-f283-40d9-b866-068b27d05379.png)

**Comment by FiveOFive** [comment]
Closing stale issues
