### ISSUE TITLE
Lots of log noise from pubsub

### ISSUE THREAD

**Issue by rbliss** [FiveOFive/ws-pubsub#7]
Anytime a page is refreshed, the socket gets an error `ECONNRESET`. Since pubsub uses `console.log` everywhere, this gets spit out into the logs. See https://github.com/FiveOFive/pubsub-ws/blob/a0ba6fd5c5c217b909a59d21fc9b3ca12a89de36/src/webSocket.ts#L25

Is it possible to pass in our own logger for better control, and perhaps suppress `ECONNRESET` on the socket error?

**Comment by rbliss** [comment]
Example from logs
<img width="547" alt="Screenshot 2024-10-25 at 12 42 00 PM" src="https://github.com/user-attachments/assets/4fbed76d-4526-4708-b793-3af19c1e64d7">

**Comment by FiveOFive** [comment]
Implemented https://github.com/FiveOFive/pubsub-ws/blob/283a22e61fdefe6e1a7c5b85e82da7f2d7d8a791/src/logger.ts
